export const ADD_SERVER = 'ADD_SERVER';
export const ADD_SERVERS = 'ADD_SERVERS';
export const UPDATE_SERVER = 'UPDATE_SERVER';
export const DELETE_SERVER = 'DELETE_SERVER';
export const CURRENT_SERVER = 'CURRENT_SERVER';
export const CURRENT_CHANNEL = 'CURRENT_CHANNEL';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_MESSAGES_BEFORE = 'ADD_MESSAGES_BEFORE';
export const ADD_MESSAGES_AFTER = 'ADD_MESSAGES_AFTER';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const SET_PRESENCE = 'SET_PRESENCE';

export const ADD_FILE = 'ADD_FILE';
export const REMOVE_ALL_FILES = 'REMOVE_ALL_FILES';
